### ISSUE TITLE
Change UI color

### ISSUE THREAD

**Issue by area57** [DavidKinder/Git#12]
hi, is it possible to change the UI Color before compiling? and if so where do i have to define the colors

**Comment by DavidKinder** [comment]
I'm not quite sure what you mean by "UI Color"? But the Git interpreter doesn't have a UI of its own, it has to be linked to a library that implements Andrew Plotkin's Glk specification: the Windows binaries on the Releases page for Git are linked with my [Windows Glk](https://github.com/DavidKinder/Windows-Glk/). There is a preferences dialog in Windows Glk applications that lets you set the default fore and background colours, if that's what you mean, and changing the Windows Glk code would allow you to change the UI.
