### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by mgscab** [DavidKinder/Git#13]
I do not know how to code, but I attempted to follow the instructions as best I could and got this as an error upon attempting to build 
1>------ Build started: Project: Git, Configuration: Debug Win32 ------
1>Building help file...
1>The system cannot find the path specified.
1>The system cannot find the file specified.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'help\Git.hhp' exited with code 1.
1>Done building project "Git.vcxproj" -- FAILED.
If it is something very obvious I am sorry for taking up your time.

**Comment by DavidKinder** [comment]
That error is just about building the help file, I had forgot that that requires Html Help Workshop in order to work. I've updated the build instructions to mention this, try installing Html Help Workshop from the link given and it ought to work.
