### ISSUE TITLE
Please comment on Glulx byte-swap RFC

### ISSUE THREAD

**Issue by dfoxfranke** [DavidKinder/Git#21]
I've opened https://github.com/iftechfoundation/ifarchive-if-specs/issues/13 with a brief proposal to add a set of byte-swapping instructions to Glulx. Opening this issue here as well to make sure Git maintainers have the opportunity to read and comment.

**Comment by DavidKinder** [comment]
Comment added to the IF Specs repository: I'd prefer support via `accelfunc` than new opcodes.
