### ISSUE TITLE
-lm option needs to be set in gcc 5.4

### ISSUE THREAD

**Issue by curiousdannii** [DavidKinder/Git#6]
I'm a complete newbie at C, but I've found that I needed to add -lm to LIBS in the Makefile in order to compile it with gcc 5.4, which is the default for Ubuntu 16.04.

I don't know if that's a kind of change you want to have by default in the Makefile, or if it would cause problems for other compilers or other OSes. But I'm suggesting it here just in case.

**Comment by BroadcastGames** [comment]
What are the symptoms if you don't set this?

**Comment by curiousdannii** [comment]
It won't compile. I don't remember exactly what compilation errors are shown.

**Comment by BroadcastGames** [comment]
Request: can the Makefile advice of "Best settings for GCC 2.95. This generates faster code than
 GCC 3, so you should use this setup if possible." be updated to more modern choice of GCC 4.9 vs. GCC 5? 2.95 vs. 3 is outdated.

**Comment by DavidKinder** [comment]
-lm added to LIBS in Makefile
